apply plugin: 'com.android.application'

android {
    namespace = "nl.kmartin.sceneformshowcase"

    compileSdk = 37

    defaultConfig {
        applicationId = "nl.kmartin.sceneformshowcase"
        minSdk = 30
        targetSdk = 37
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled = true
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }

    buildFeatures {
        dataBinding = true
        buildConfig = false
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

ext {
    appCompatVersion = '1.7.1'
    constraintLayoutVersion = '2.2.1'
    jUnitVersion = '4.12'
    testRunnerVersion = '1.2.0'
    espressoVersion = '3.2.0'
    materialVersion = '1.12.0'
    lifecycleExtensionsVersion = '2.1.0'
    retrofitVersion = '2.4.0'
    okHttpVersion = '3.12.0'
    rxAndroidVersion = '2.1.1'
    rxjavaVersion = '2.2.10'
    gsonVersion = '2.8.5'
    glideVersion = '4.9.0'
    zxingVersion = '3.5.0'
    multidexVersion = '2.0.1'
    playServicesVisionVersion = '18.0.0'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation "androidx.appcompat:appcompat:$appCompatVersion"
    implementation "androidx.constraintlayout:constraintlayout:$constraintLayoutVersion"

    testImplementation "junit:junit:$jUnitVersion"
    androidTestImplementation "androidx.test:runner:$testRunnerVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$espressoVersion"

    // Material
    implementation "com.google.android.material:material:$materialVersion"

    // Architecture Components
    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycleExtensionsVersion"

    // Retrofit
    implementation "com.squareup.retrofit2:retrofit:$retrofitVersion"
    implementation "com.squareup.retrofit2:adapter-rxjava2:$retrofitVersion"
    implementation "com.squareup.retrofit2:converter-gson:$retrofitVersion"

    // HTTP logging
    implementation "com.squareup.okhttp3:logging-interceptor:$okHttpVersion"

    // RxJava
    implementation "io.reactivex.rxjava2:rxjava:$rxjavaVersion"
    implementation "io.reactivex.rxjava2:rxandroid:$rxAndroidVersion"

    // Gson
    implementation "com.google.code.gson:gson:$gsonVersion"

    // Glide
    implementation "com.github.bumptech.glide:glide:$glideVersion"
    annotationProcessor "com.github.bumptech.glide:compiler:$glideVersion"

    // ARCore / Sceneform
    implementation "com.google.ar.sceneform.ux:sceneform-ux:$sceneform_version"
    implementation "com.google.ar.sceneform:assets:$sceneform_version"
    implementation "com.google.ar:core:1.35.0"

    // QR scanning
    implementation "com.journeyapps:zxing-android-embedded:$zxingVersion"

    // Multidex
    implementation "androidx.multidex:multidex:$multidexVersion"

    // Google Play Services
    implementation "com.google.android.gms:play-services-vision:$playServicesVisionVersion"

    // Permissions
    implementation 'io.github.nishkarsh:android-permissions:0.1.7'
}

apply plugin: 'com.google.ar.sceneform.plugin'